language: r
sudo: false
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
    - secure: RXpswOOXf6qEOfiZWZXV4C69X9ObrfKFWrOi5WY/m3K844uL3Dxeeqr+Ei9JlIVAS1lBp1Hpt5In4CXTXKrfdwuN7XpOg1EId6hX8UJ5BpOCSDJ9HA/R80JyaeC5Vx9Uiqbxji9x8Zw7awBV/PqnNcUI9NcUmKtut2RsNsBALvs=

repos:
  XRAN: http://yihui.name/xran

before_install:
  - "wget -q http://yihui.name/xran/.gitconfig -O ~/.gitconfig"

after_success:
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"
