# it is not really python, but there is no R support on Travis CI yet
language: python

# environment variables
env:
  - R_LIBS_USER=~/R

# install dependencies
install:
  - sudo apt-add-repository -y 'deb http://cran.rstudio.com/bin/linux/ubuntu precise/'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update
  - sudo apt-get install r-base-dev r-cran-rcpp qpdf texinfo texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
  - "[ ! -d ~/R ] && mkdir ~/R"
  - R -e '.libPaths(); sessionInfo()'
  - Rscript -e 'install.packages("servr", dep = TRUE, repos = "http://cran.rstudio.org")'
  - cd ..; rm -f *.tar.gz; R CMD build servr; R CMD INSTALL servr_*.tar.gz

# run tests
script:
  - R CMD check servr_*.tar.gz
